### ISSUE TITLE
display component of the cached count. 

### ISSUE THREAD

**Issue by veeramarni** [cdmbase/fullstack-pro#130]
**Is your feature request related to a problem? Please describe.**
Need to write a small component displaying the counter result from button `Click to get cached counter` next to the button. 

**Describe the solution you'd like**
All the graphql part is generated, it only requires displaying the result from the graphql query. And showing in a pretty way. 

**Describe alternatives you've considered**
**Additional context**

![image](https://user-images.githubusercontent.com/3382355/86349994-fcdc4400-bc2f-11ea-826c-8e463b6237a2.png)

**Comment by blue113** [comment]
**Is your feature request related to a problem? Please describe.**
From the apollo client, we can use context. With that context, we can use cached query result when that query is already called before.

**Describe the solution you'd like**
We can get query result in several ways. Using the component which is provided from react-apollo.
Also using hooks provided from react-apollo.

**Describe alternatives you've considered
Additional context**
Regarding this question, I'd like to clarify more .

**Comment by blue113** [comment]
Hello, 
Can we move to next step?
